# Generated by Django 5.1.4 on 2025-01-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("parser_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseStatistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_statistics",
                        to="parser_app.author",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AlterField(
            model_name="publicationstatistics",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_statistics",
                to="parser_app.author",
            ),
        ),
        migrations.CreateModel(
            name="MonographStatistic",
            fields=[
                (
                    "basestatistic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="parser_app.basestatistic",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("parser_app.basestatistic",),
        ),
        migrations.CreateModel(
            name="TextbookStatistic",
            fields=[
                (
                    "basestatistic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="parser_app.basestatistic",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("parser_app.basestatistic",),
        ),
    ]
