# Generated by Django 5.1.4 on 2025-01-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "parser_app",
            "0002_basestatistic_alter_publicationstatistics_author_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basestatistic",
            name="author",
        ),
        migrations.RemoveField(
            model_name="basestatistic",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="monographstatistic",
            name="basestatistic_ptr",
        ),
        migrations.DeleteModel(
            name="TextbookStatistic",
        ),
        migrations.DeleteModel(
            name="BaseStatistic",
        ),
        migrations.DeleteModel(
            name="MonographStatistic",
        ),
    ]
