# Generated by Django 5.1.4 on 2025-01-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0003_remove_basestatistic_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monograph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monographs",
                        to="parser_app.author",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Textbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="textbooks",
                        to="parser_app.author",
                    ),
                ),
            ],
        ),
    ]
