# Generated by Django 5.1.4 on 2025-01-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_app", "0005_basestatistic_remove_textbook_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basestatistic",
            name="author",
        ),
        migrations.RemoveField(
            model_name="basestatistic",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="textbookstatistic",
            name="basestatistic_ptr",
        ),
        migrations.AlterField(
            model_name="publicationstatistics",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="parser_app.author",
            ),
        ),
        migrations.DeleteModel(
            name="MonographStatistic",
        ),
        migrations.DeleteModel(
            name="BaseStatistic",
        ),
        migrations.DeleteModel(
            name="TextbookStatistic",
        ),
    ]
