# Generated by Django 5.1.4 on 2025-01-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("parser_app", "0006_remove_basestatistic_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonographStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Год")),
                (
                    "monograph",
                    models.PositiveIntegerField(default=0, verbose_name="Монография"),
                ),
                (
                    "textbook",
                    models.PositiveIntegerField(default=0, verbose_name="Учебник"),
                ),
                (
                    "tutorial",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Учебное пособие"
                    ),
                ),
                (
                    "tutorial_griff",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Учебное пособие (гриф)"
                    ),
                ),
                (
                    "article_russian_journal",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Статья из российского журнала"
                    ),
                ),
                (
                    "article_foreign_journal",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Статья из зарубежного журнала"
                    ),
                ),
                (
                    "izvestia_vstu",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Известия ВолгГТУ"
                    ),
                ),
                (
                    "journals_vstu",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Журналы ВолгГТУ"
                    ),
                ),
                (
                    "article_russian_collection",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Статья из российского сборника"
                    ),
                ),
                (
                    "article_foreign_collection",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Статья из зарубежного сборника"
                    ),
                ),
                (
                    "theses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Тезисы докладов"
                    ),
                ),
                (
                    "educational_complex",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Учебно-методический комплекс"
                    ),
                ),
                (
                    "deposited_manuscript",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Депонированная рукопись"
                    ),
                ),
                (
                    "patent_document",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Патентный документ"
                    ),
                ),
                (
                    "certificate",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Свидетельство"
                    ),
                ),
                (
                    "other_publications",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Прочие публикации"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="parser_app.author",
                    ),
                ),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Монографическая статистика",
            },
        ),
        migrations.DeleteModel(
            name="PublicationStatistics",
        ),
    ]
